In [ ]:
import numpy as np

a= np.array([[1,2,3,4],
             [5,6,7,8]
            ])
def describe(array):
    print("array:{}\n arrayShape:{}\n arrayFormat:{}".format(array,array.shape,array.dtype))

describe(a)

#come accedo ad una cella dell array? Uso l'accesso con indexing multidimensionale nello stile numpy,così da accedere più velocemente
#ed in maniera migliore alla memoria, un np.array si differenzia da un array python da fatto che la porzione di memoria del np.array
#è tutta contigua

#Quesito: "Voglio prendere il valore 1"
#corretto:
print(a[0,0])

#errato:
print(a[0][0])

#con entrambe le tecniche riusciamo ad avere lo stesso risultato, però nel modo errato facciamo due accessi alla memoria, il primo 
#per prendere tutta la prima riga e poi da questa prendiamo il primo elemento, invece nel modo corretto numpy accede direttamente 
#all' elemento in posizione [0,0], prima fa una vista su a[0] ,e poi prende il primo elemento, quindi non crea la lista a[0] come 
#farebbe python ma fa una vista
'''
inoltre nelle liste python non in stile numpy, posso solo fare print(a[0][0]), da qui capiamo il potere di numpy
'''

array:[[1 2 3 4]
 [5 6 7 8]]
 arrayShape:(2, 4)
 arrayFormat:int64
1
1


ESERCIZIO
Crea un array da 1 a 20
Trova media e somma
Moltiplica tutto per 3
Estrai i numeri pari

In [20]:
array = np.arange(1,21,1)
somma = np.sum(array)
media = np.mean(array)
array1 = array * 3 #questa operazione crea un nuovo array, per fare una copia profonda di un array bisogna fare
#array = array.copy(), invece se faccio array1 = array oppure array1 = array[:], i due array stanno condividendo
#la stessa porzione di memoria,se modifico uno allora modifico anche l'altro
print("Somma : {} ".format(somma))
print("Mean : {}".format(media))
print(array)
print(array1)

numeriPari = array1[array1 % 2 == 0]
print(numeriPari)

Somma : 210 
Mean : 10.5
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]
[ 6 12 18 24 30 36 42 48 54 60]
